host = "localhost"
exchangeName = "proximity-exchange"
CrawledURLQueue = "crawler-queue"
ScrapedNewsQueue = "scraper-queue"
SummarizerPriorityQueue = "summarizer-priority-queue"
SummarizerNonPriorityQueue = "summarizer-non-priority-queue"
SummarizedNewsQueue = "summarizer-completed-queue"
